### ISSUE TITLE
Please continue working on mc-crash-analyzer

### ISSUE THREAD

**Issue by Bluscream** [antoinegag/antoinegag#1]
Thanks !!❤️

**Comment by antoinegag** [comment]
Hi @Bluscream! I am no longer involved in the Minecraft scene and don't have time to keep working on this project unfortunately, sorry :( 

Feel free to fork it and make it better!

**Comment by Bluscream** [comment]
Okay, sad to see one more alternative go. Can you please add a link to https://crashy.net/ on the site and github repo then because people have a hard time finding a working website for it.
